### ISSUE TITLE
Toolbox and popup overlays positionning

### ISSUE THREAD

**Issue by jano42** [google/blockly#169]
I have a problem with the toolbox and popup positioning (like drop down menus)
I use a bootstrap site, and blockly into a *bootstrap modal window*.

In fact the **toolbox and popups are not shown** correctly (placed behind the modal).

I've inspected to html generated code, and I've seen that 
 * the toolbox html is **inserted at the end of the `document.body`** (core/toolbox.js, line 103)
 * the popups are also inserted at the end of the `document.body`** (widgetdiv.js line 64)

Is it possible to change the insertion behavior by placing those items (toolbox and widgetdiv) in the injection container. (at the end or next to it). The aim is that those items should keep some properties of their html parents. 

If my blockly is inside a modal; then the toolbox and the popup will be compatible with modal (not displayed behind,....)

**Comment by previ** [comment]
Same problem with an jqm-based web app.
My quick-and-dirty fix (still testing it...) is to insert this code after Blockly.inject(...)
        $('.blocklyToolboxDiv').appendTo('#your-injection-container');
        $('.blocklyTooltipDiv').appendTo('#your-injection-container');
        $('.blocklyWidgetDiv').appendTo('#your-injection-container');

**Comment by jano42** [comment]
Thanks for your answer. I've also though about this 'quick & dirty' fix

**But it partially work.**

The toolbox is **not placed correctly**

![2015-08-31 15_36_06-clipboard](https://cloud.githubusercontent.com/assets/3135683/9579907/1f7c0230-4ff6-11e5-9b2c-534ae7f460fa.png)

Dropdown menus are **also not at the right place** (especially when my browser use scrollbars to display my page - not the blockly scrollbars)

**Comment by carlosperate** [comment]
The reason the toolbox is appended to the `body` instead of the injected element is to fix RTL bugs: https://github.com/google/blockly/issues/141#issuecomment-125868767

Since the toolbox has an absolute position, wouldn't increasing the z-index of the `blocklyToolboxDiv` allow you to display it in the bootstrap modal? However, you would still have an issue if the modal content was large enough to be scrollable.

**Comment by jano42** [comment]
I've tried the solution with z-index; but I still have artifacts.

* When I close the modal (so close the blockly editor), then the toolbox is still displayed (closed only when clocking on it).

According to me, it is not a durable solution of inserting overlay elements (toolbox, tooltip, dropdown,...) at the end of body because in that case, they don't have the same css as the blockly svg...
So integrating blockly in websites; probably will have several display bugs (like boostrap modals,...)

Maybe an option would do the trick. (like overlayPosition: body|injectionContainer)
With such an option it could fix the RTL bugs: #141  and then may be integrable in some websites...

**Comment by carlosperate** [comment]
> When I close the modal (so close the blockly editor), then the toolbox is still displayed (closed only when clocking on it).

I believe you can add a callback on modal close, so if you execute `Blockly.fireUiEvent(window, 'resize')` on that callback it should remove the toolbox as well.

**Comment by jano42** [comment]
Thanks for this fix; it should work, but there are still scrolling problems.

The best way would be to move the div in the injection container, before SVG, and just disable the stye setting for left and top css properties. But removing style settings implies a core blockly modification. But I don't want to do. (toolbox.js line 156, function: Blockly.Toolbox.prototype.position)


Unfortunately, there are **too much 'ugly' tricks to make it display correctly.**

 I prefer wait to have a **fully integrable Blockly** (either by an option, or by any other solution). 

I think similar problems will occurs in every CSM like Drupal, Wordpress, Joomla; when the Blockly is not displayed directly in the document.body (in modals, in a js window,...).

**Comment by jano42** [comment]
### To reproduce

Edit playground.html

Insert those lines at line 54 (after all js script references)

```html
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
```

then at line 527 (before closing body tab)

```javascript
  <script>
function createBlockly() {

	Blockly.inject('blocklyDivModal',
            {
                comments: true,
                disable: true,
                collapse: true,
                grid: {
                    spacing: 25,
                    length: 3,
                    colour: '#ccc',
                    snap: true
                },
                readOnly: false,
                realtime: false,
                scrollbars: true,
                toolbox: document.getElementById('toolbox'),
                zoom:
                {enabled: true,
                    controls: true,
                    wheel: true,
                    maxScale: 2,
                    minScale: .1,
                    scaleSpeed: 1.1
                }
            });

		
}

//when modal shown, inject blockly
$('#myModal').on('shown.bs.modal', function () {
  createBlockly();
})

//on button click, display modal
$('#buttonShowModal').unbind('click').bind('click', function() {
	$('#myModal').modal();
});
</script>
```

That'all
Just run the playground page, and click the "Open Modal" button... and see...

**Comment by jano42** [comment]
Another issue:
Each time a click is done in SVG (either on a block, or elsewhere), **then the modal height grows** !!

**Comment by carlosperate** [comment]
> Each time a click is done in SVG (either on a block, or elsewhere), then the modal height grows !!

Information about that can be found in: https://github.com/google/blockly/issues/146

**Comment by jano42** [comment]
I've created a pull request https://github.com/google/blockly/pull/181 to fix all above problems.

**Comment by carlosperate** [comment]
@jano42 you example code for replication does not include an open modal button.

**Comment by ctrowat** [comment]
We are also having 2 problems within our app because of the toolbox (and other objects) being injected into the document body.  


1) When dynamic content above (and unrelated to) the blockly div is resized the toolbox moves outside of the blockly window, this is ugly and resizing content in another unrelated div should not cause display issues with blockly


2) When we open a modal dialog within our app we hide everything inside of our parent container div.  The blockly toolbox is injected at a level higher than this and remains on screen when all content should be hidden.


It is mentioned in #141 that one should simply fire the resize event in blockly and that would patch around issue 1 for us (but not the second one) however that feels like a hack and in our case it is not possible as the component that is changing it's size and the blockly div are completely unrelated.  It is also mentioned in #141 that this change was made as part of fixing some RTL behaviour but that Neil Fraser was not aware of how this could be related.  Can we please investigate this further and perhaps return these divs to residing within the parent blockly div?

**Comment by snoosmoomrik** [comment]
As a temporary solution you could create a custom div with a list of categories to the left of your injection container and call `workspace.updateToolbox(your_toolbox_xml_without_categories)` on list item click.
Of course it will not solve the problem with context menu but at least your toolbox will be in it's place.

**Comment by MarkusBordihn** [comment]
I run into the same issue. The toolbox should be injected into the node which was defined by Blockly.inject and not at the highest level in the dom tree. (Z-index is useless in this case)

With the current implementation its impossible to place an layer over blockly and if you remove the injected div, the toolbox still exists.

Please fix this.

**Comment by rachel-fenichel** [comment]
Possibly fixed by #512

**Comment by NeilFraser** [comment]
#512 changed everything.  Thus if something like this bug still exists, then it is actually an entirely new bug and should be refiled.
