### ISSUE TITLE
Dropdowns break on pages with multiple instances of Blockly

### ISSUE THREAD

**Issue by acbart** [google/blockly#183]
I experience this bug in Chrome on Windows, and IE on Windows.

If you load up a page with multiple instances of Blockly, all but one will have broken dropdowns (it seems like usually the first one will work, although in some cases it seems like none of them will work). Specifically, if you click the dropdown, the dropdown will have a height of only 2. I believe these two pixels represent the top shadow and bottom shadow of the box. 

![image](https://cloud.githubusercontent.com/assets/897227/10036258/1820741a-6173-11e5-897f-038c3b382e43.png)

If you click a functional dropdown and open that menu, the rest of the dropdowns start working fine.

I've set up a test canvas with two instances demonstrating this problem, if you click a block with a dropdown in the second instance you can trigger the bug: https://dl.dropboxusercontent.com/u/23141976/google-blockly-2d60d94/google-blockly-2d60d94/demos/generator/index.html

**Comment by acbart** [comment]
I believe the line of code that causes this is:
https://github.com/google/blockly/blob/master/core/widgetdiv.js#L144

If the difference in the two values is negative (`anchorY` > `windowSize`), then the `style.height` will not be changed. The arguments to the function suggest that `anchorY` should be window coordinates, but the following call seems to pass in body coordinates:
https://github.com/google/blockly/blob/master/core/field_dropdown.js#L195

I believe this is because the `xy` field is originally set using `getAbsoluteXY_` function, which is giving body coordinates unadjusted for scrolling.

**Comment by carlosperate** [comment]
Did you fix the issue in https://dl.dropboxusercontent.com/u/23141976/google-blockly-2d60d94/google-blockly-2d60d94/demos/generator/index.html ? I am unable to replicate under Windows 8.1 with Chrome 45, IE11 or Firefox 41. However in IE the page scrolls down as soon as I open a dropdown menu in the lower workspace, which I did not expect.

**Comment by acbart** [comment]
Still a problem for me on that page, I'm also on Chrome 45 on Windows 8.1. You tried the dropdown in the second instance before the first instance? 

![image](https://cloud.githubusercontent.com/assets/897227/10050447/6363db5c-61ea-11e5-8ce6-912ea882e95b.png)

**Comment by acbart** [comment]
Just a quick thought: if you have a very large monitor, you won't trigger the error because your window size will be able to overcome the limitation. I can replicate that effect by zooming out.

**Comment by carlosperate** [comment]
Never mind, got it to behave like that if the drop down area is outside of the initial page viewport.

**Comment by acbart** [comment]
Yep, that explains the variability I experienced - sometimes it was breaking on pages with only a single instance, but in those cases it was still further down on the page, causing issues :)

**Comment by acbart** [comment]
Do you know what the adjusted call should be? We go live tomorrow and I'm not exactly sure what to adjust the offset by.

**Comment by carlosperate** [comment]
I don't really have the time to look into it properly for a couple of days, sorry about that, this is actually my bad. If you are in a rush you can just revert the changes to the widget https://github.com/google/blockly/pull/131/files

**Comment by acbart** [comment]
Thanks, rolling back those changes should definitely hold us over!

**Comment by NeilFraser** [comment]
Working on this now.  I just pushed a small fix that corrects the workspace focus when a block is clicked.

Multiple Blockly instances on a single page is something that doesn't get used a lot (Block Factory and some readonly help are the only examples that come to mind), so bugs can easily pop up here.  But it is something that should work correctly and I'll squash anything I find.

**Comment by NeilFraser** [comment]
Hmm, the above fix I just made seems to have made the problem go away, at least for me.  Can you confirm?

**Comment by acbart** [comment]
Can't confirm, I'm afraid the problem still occurs for me even with the latest fix.

**Comment by NeilFraser** [comment]
Ah, progress.  This has nothing to do with multiple Blockly instances.  It is simply the effect of having a page scroll down then a dropdown gets misaligned.  Ok, that makes things easier to debug.

**Comment by NeilFraser** [comment]
Fixed.  Thanks for reporting this.  I should have paid closer attention to Carlos' comments, he was way ahead of me on this issue.
