### ISSUE TITLE
Labels With Different Font Size are Not Rendered Correctly

### ISSUE THREAD

**Issue by BeksOmega** [google/blockly#2694]
**Describe the bug**

Labels can be passed a class. If this class gives the label a different font size, it renders outside the bounds of the block.

**To Reproduce**

1. Add the following block definitions to the test blocks file:
```
{
    "type": "example_text_class",
    "message0": "%1",
    "args0": [
      {
        "type": "field_label",
        "name": "NAME",
        "text": "default",
        "class": "custom-text-class"
      }
    ],
    "colour": 230,
  },
  {
    "type": "example_text_class_image",
    "message0": "%2 %1",
    "args0": [
      {
        "type": "field_image",
        "src": "https://www.gstatic.com/codesite/ph/images/star_on.gif",
        "width": 50,
        "height": 50,
        "alt": "*",
        "flipRtl": false
      },
      {
        "type": "field_label",
        "name": "NAME",
        "text": "default",
        "class": "custom-text-class"
      }
    ],
    "colour": 230,
  },
```
2. Add the following css to the playground:
```
.custom-text-class {
  fill: black;  /* for visibility*/
  font-size: 50px;
}
```
3. Load the playground.
4. Import the following XML.
```
<xml>
  <block type="example_text_class"/>
  <block type="example_text_class_image" y="50"/>
</xml>
```
5. Observe how the text is rendered oddly. Especially on the block with the image.

**Expected behavior**

I expect the top of the text to be aligned with the top of the block (as that seems to be the [current official behavior](https://github.com/google/blockly/issues/1430#issuecomment-342672979)). The block should encapsulate all of the text.

**Screenshots**

![Text_Classes](https://user-images.githubusercontent.com/25440652/61754229-38efff00-ad67-11e9-90ba-58f0ca21efc7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75

(I believe this is not browser specific)

**Stack Traces**

N/A

**Additional context**

I think the problem is probably caused by [this line](https://github.com/google/blockly/blob/bb8fb10ef7c3eea9a83a96b2144199b4a967b02b/core/field_label.js#L84) being a constant (since [size_.height is constant](https://github.com/google/blockly/blob/bb8fb10ef7c3eea9a83a96b2144199b4a967b02b/core/field_label.js#L47)).

The y attribute is also set by the abstract field class [here](https://github.com/google/blockly/blob/bb8fb10ef7c3eea9a83a96b2144199b4a967b02b/core/field.js#L290), and then overriden by the above line.

I know all of the field sizing stuff is a little iffy atm, I just think this is an important test case.

**Comment by rachel-fenichel** [comment]
@samelhusseini since I know you're looking at labels.

**Comment by samelhusseini** [comment]
Yup

**Comment by samelhusseini** [comment]
Fixed.

**Comment by BeksOmega** [comment]
From my testing I think this still occures. This issue is for classes that are applied directly to the label field.

**Comment by samelhusseini** [comment]
Sorry I meant to close the other one :)

**Comment by sahilrastogi94** [comment]
Is this still being looked at?

**Comment by BeksOmega** [comment]
> Is this still being looked at?

I don't believe so, but we are going to be [refactoring how styling works ](https://groups.google.com/g/blockly/c/pqM6iYmYXt8/m/tdNmmEUqAQAJ)in the near future.
