### ISSUE TITLE
Text fields re-sizing is broken after the workspace regains visibility

### ISSUE THREAD

**Issue by samelhusseini** [google/blockly#2811]
**Describe the bug**

Text fields don't adjust when the Blockly workspace regains visibility. 

**To Reproduce**

1. Go to the Blockly playground.
2. Hide the workspace ``Blockly.mainWorkspace.setVisible(false);``
3. Import a block to the workspace that contains a text field.
4. Show the workspace ``Blockly.mainWorkspace.setVisible(true);``
5. Notice how even after a re-render, the text field doesn't adjust its size accordingly. 

**Expected behavior**

The text field should adjust it's size after a re-render, just like other fields. 

**Screenshots**

<img width="307" alt="Screen Shot 2019-08-13 at 1 43 15 PM" src="https://user-images.githubusercontent.com/16690124/62976049-a1635680-bdd0-11e9-93a5-5599bc8ed4fc.png">

**Additional context**

This problem only occurs on develop, so something must've changed that broke this. 

This bug here is more or less the same, https://github.com/google/blockly/issues/1688
However it defines the problem in master. Don't have full context here, but I don't repro this on master.

**Comment by BeksOmega** [comment]
Problem is [this line](https://github.com/google/blockly/blob/4efa0dad1f2c882234759d3ba7ecd0ebd95a4c77/core/xml.js#L533) is calling render when it shouldn't (b/c the workspace isn't visible yet).

It could be wrapped in an isVisible() check:
```
if (workspace.isVisible()) {
  for (var i = blocks.length - 1; i >= 0; i--) {
    blocks[i].render(false);
  }
}
```
But then scrollbars don't seem to resize correctly.

Another option would be to:
* First pass the visibility down to all the fields, connections, etc before rendering.
* Then don't allow the fields to cache their widths if render is called while they are invisible.

But eliminating the bad render call all together would be more efficient.

**Comment by samelhusseini** [comment]
Fixed.

**Comment by RoboErikG** [comment]
This is still happening on the code demo if you paste blocks into the xml tab then switch back to the blocks tab:
![image](https://user-images.githubusercontent.com/11066279/66451127-ecd06480-ea0f-11e9-95c4-8e82e5f8cfc4.png)

**Comment by RoboErikG** [comment]
Repro steps:
1. Open demos/code/index.html
2. Switch to the xml tab
3. Paste the below xml
4. Switch back to the blocks tab

```
<xml xmlns="https://developers.google.com/blockly/xml">
  <block type="controls_if" id="isl,3EXhyH{0:iYXUdwH" x="163" y="63">
    <value name="IF0">
      <block type="logic_boolean" id="(!GZ3Vr:u=O%AHxt-$!)">
        <field name="BOOL">TRUE</field>
      </block>
    </value>
    <statement name="DO0">
      <block type="text_print" id="%JYt5sZ-3ZK$cyY7p94|">
        <value name="TEXT">
          <shadow type="text" id="l]JtBR?,P)LZiKwBvp!+">
            <field name="TEXT">abc</field>
          </shadow>
        </value>
      </block>
    </statement>
  </block>
</xml>
```

**Comment by samelhusseini** [comment]
Good repro. It's a separate issue but the same side-effect, the above is causing a crash. Should definitely look into it though.
