### ISSUE TITLE
onError method for XML parsing

### ISSUE THREAD

**Issue by ewpatton** [google/blockly#3025]
**Is your feature request related to a problem? Please describe.**

In App Inventor we allow people to plug a text block into a math block iff the text block's text parses as a number. However, since type checking of connections doesn't occur when a field changes, we have found that people will change the text to a non-numeric value. Next time the project loads, the type check on the connection runs and an error is thrown since the blocks shouldn't be connected. This can also occur when the method signature has changed and we are loading the workspace before evaluating an upgrade function to handle the changed signature.

**Describe the solution you'd like**

We'd like to add an onError method to the XML parser that would report the error. The default onError behavior could be to throw an error like the current behavior. However, we'd prefer to be able to capture these errors and use them to inform the developer about how to fix the issue rather than have the blocks workspace fail to load.

**Describe alternatives you've considered**

**Additional context**

We're willing to implement this feature and backport it to Blockly if the Google team agrees that it would be useful.

**Comment by RoboErikG** [comment]
I'm not opposed to an API to make handling XML errors easier, but I'm not sure I understand this case and what the proposed solution might look like.

Is the proposed solution to have domToWorkspace/domToBlock add a try/catch wrapper and call an onError method if something goes wrong? Is there a difference between that and a developer wrapping it in a try catch themselves? And who are you going to tell how to fix it, AppInventor's user who is coding in Blocks?


As to the set of steps that are causing the bad xml, that might be a good reason for us to add a changelistener API to field that gets called in doValueUpdate_. That way you could update the type checks when the value changes.

**Comment by BeksOmega** [comment]
> As to the set of steps that are causing the bad xml, that might be a good reason for us to add a changelistener API to field that gets called in doValueUpdate_. That way you could update the type checks when the value changes.

I think you should be able to handle this case with a normal validator.

**Comment by ewpatton** [comment]
I’m not sure validation would work as currently implemented in Blockly. My understanding, and please correct me if I’m mistaken, is that connection checks occur based on the current state of a block, not the potential future state. We would want the option to kick the block out if and only if the text block no longer contains a valid value (but not on individual keystrokes in case someone fat fingers something). We would need a way to either tell the connection check method that the block will have a future state or we would need to be able to swap the new value for old, call the check, and if it fails kick out the block. I don’t think the order of operations is correct here w.r.t. the validator, change, and (possibly) move event, but I’m on my phone so can’t check against the code. 

There is a second use case that I hadn’t originally mentioned around language upgrades where we change the signature of a method. We had to hack a change into Blockly core to bypass error checking because we have upgrade code that runs over the workspace to handle the semantic changes. If you let the XML parser throw an error you just end up with a partially constructed workspace that is not useful for anything. You don’t even get any of the blocks past that point in the XML because of the thrown error. Instead, we parse the entire workspace without throwing errors on malformed blocks and then run the upgraders to ensure that the blocks conform to the new language spec rather than the old. We would also replace that hack with the approach I proposed in my original post.

**Comment by BeksOmega** [comment]
>connection checks occur based on the current state of a block, not the potential future state

You are correct.

>We would want the option to kick the block out if and only if the text block no longer contains a valid value (but not on individual keystrokes in case someone fat fingers something). 

I think I can give you a recommendation for this specific case, but with regard to the rest of your upgrading/error handling stuffs I have no relevant input.

So as you noted, you only want to handle changes when the user is done with their input. Blockly core also ran into this problem when implementing [procedure blocks](https://github.com/google/blockly/blob/4efa0dad1f2c882234759d3ba7ecd0ebd95a4c77/blocks/procedures.js#L573), so there is hook for this usecase.

Just assign a function to the text input field's onFinishEditing_ property:
```
Blockly.Blocks['example_block'] = {
  init: function() {
    var field = new Blockly.FieldTextInput("default");
    field.onFinishEditing_ = this.changeListener;
    this.appendDummyInput()
        .appendField(field, "FIELDNAME");
  },

  changeListener: function(newValue) {
    console.log('doing the chang listening');
  }
};
```
And it will be called, with the new value, when the textinput widget closes.

Note that this is sort of hacky, and it does have a [tracking issue](https://github.com/google/blockly/issues/2496) to make it better, but it's an official kind of hacky, so it shouldn't break on ya'.

**Comment by RoboErikG** [comment]
@ewpatton regarding the upgrade scenario: We've generally done this (and I believe Scratch does too) by keeping the old block definition around, but swapping in a new block definition to the toolbox. This lets you load the workspace and then swap out blocks as you'd like.

That being said, it is a pretty involved solution and means you need to keep around a bunch of old block definitions.  What would the change to the XML parser look like to support updating in place?

And regarding values that should change the type check. I think that's a different problem as ideally it would pop the block out as soon as the user finishes making the edit so they have the immediate feedback. As @BeksOmega pointed out, there's a somewhat hacky solution using onFinishEditing_ that we might want to formalize a bit more as a callback.

**Comment by amber-cd** [comment]
For what it's worth, we've actually managed to break XML a few parsing through various methods (a memorable recent one was when we naively attempted to wrap a block around some of our saved XML via basic text manipulation, only to wind up encapsulating multiple block stacks in one statement block in a few of them) and have been frustrated by the lack of error information when debugging such issues. Even just wrapping a try/catch around our domToWorkspace(xmlToDom) setup with logging often results in quiet failures without a lot in the way of error messages, and it's been a pain when trying to figure out some scenarios where try to open a saved workspace, only for some or all of our blocks to just disappear.

**Comment by BeksOmega** [comment]
Hey @ewpatton, since I'm looking into the serialization/versioning stuff again, I'm just wondering if there's still a use case for this.

I think we fixed the text vs number problems with https://github.com/mit-cml/appinventor-sources/pull/2177 and https://github.com/mit-cml/appinventor-sources/pull/2175.

Now, if we assume that all upgraders are run on the XML version of the save (so before anything gets passed to `domToWorkspace`) are there any other use cases for this? Or is it just intended to support workspace-style upgraders to make the versioning easier?

I know this is an old issue so I'm sorry to dig it up haha. If you have any more info it would be much appreciated :D But if not that's totally cool!

**Comment by amber-cd** [comment]
I'm not the original posted, but we do a variety of work with XML parsing which may occasionally result in breaking XML parsing still, and we would as a result still have a use case for this.

**Comment by BeksOmega** [comment]
> I'm not the original posted, but we do a variety of work with XML parsing which may occasionally result in breaking XML parsing still, and we would as a result still have a use case for this.

Hi Amber! I didn't know you still did Blockly stuff that's awesome :D Thank you for replying!

Could you give an example of what kind of stuff you're doing, and how this hook would help you out? Eg what stuff would you do recover if onError did get triggered? If you can't share that's totally cool too! I remember you saying a lot of the stuff you work on is proprietary.

Again, thank you for your reply! I hope the Blockly library is still working well for you and your team =)

**Comment by amber-cd** [comment]
Oh, it's still working great! Sorry you haven't heard from me more recently... I do a lot of projects on our team and haven't had to do anything weird with Blockly in a while, but that's only because it's been working so far, haha.

One thing we sometimes find ourselves called to do is to programmatically update the XML for Blockly, for example if deleting or replacing application metadata referenced in a field, wrapping blocks around other blocks, etc. This can get particularly tricky because we also have some Blockly function blocks which themselves open other Blockly workspaces in order to get reusable functions, which we may have to manipulate as a part of this. Sometimes we also have to manually fix someone's saved Blockly XML if they were unable to save it themselves due to an expired session, if we need to restore an old version due to lost work, etc. I'll admit that the use case that inspired this was in large part us taking a shortcut... we needed to wrap the logic on a number of existing workspaces across different applications inside another block in a hurry, and we used text manipulation to update the XML instead of a proper XML parser, which led to some XML that, though valid XML, resulted in blocks disappearing due to Blockly's standards, and it took us ages to debug it. Kind of an obscure use case, but it's one that comes up a lot when we have to do quick-and-dirty jobs to fix app data. Having an onError handler would help us more immediately identify the problem when these things happen by letting us more specifically identify the malformed section and possibly programmatically handle some issues.

**Comment by BeksOmega** [comment]
Hi Amber! It's good to hear that the library is still working for you :D

It's great to learn about your versioning cases. From snooping aroud in other people's repos, I've seen a lot of updating field values (especially dropdown fields). And some adding of blocks (like when you add a new input - also adding something to fill it). But I haven't seen anyone doing wrapping ye, so that's a great case to hear about =)

It seems like the main problem being solved by this onError method is visibility. Like, properly alerting that something bad has happened, and giving details about what exactly it is. Do you think that that could be accomplished through a normal `throw Error("with details")` as well? Or is the `onError` method more useful?

**Comment by amber-cd** [comment]
Throwing errors would work just as well for our purposes, I think... the lack of visibility right now is the main problem.

**Comment by BeksOmega** [comment]
Cool cool, that makes sense. Visibility is definitely a problem hehe. Thank you so much for your insight on this, it has been really helpful already :D That answers all of my questions, but if you have any other thoughts about error visibility (or related serialization-y things) feel free to message me =)

**Comment by BeksOmega** [comment]
So I talked to @ewpatton a bit about this the other day. His opinion was that having an `onError` callback is important because if it just throws an error, then it's impossible to recover. Eg even if you catch the error and handle it somehow, the deserialization has been interrupted, and it's impossible to resume where you left off. So you end up with a partially deserialized workspace.

This makes sense, and is a good argument for having callbacks instead of errors. My one concern with it is that adding the possibility of recovery mid-deserialization adds too many variants to the deserializer. For example, if a block is missing an output connection there are several ways that a dev could want to handle that:
  1) Adding the missing output
  2) Making the block a top-block
  3) Deleting the block and all of its children
  4) etc

And the serialization system would need some way to cleanly handle all of these cases (and any other cases a dev may want to implement) which I don't think is possible.

As such, my feeling is that any "error handling" / language upgrading should be done as a pre-processing step before passing the serialized state to the deserializer. This keeps the systems encapsulated, makes the API clear to external developers, and reduces variants.

But if it's not possible/good to do certain operations as a pre-processing step then I could definitely be convinced otherwise.

**Comment by BeksOmega** [comment]
Closing this  based on the reasoning above. Anyone feel free to reopen.

**Comment by BeksOmega** [comment]
Another request for something like this: https://groups.google.com/g/blockly/c/erdn-dDzfgo/m/v9Pu-7G9BAAJ
