### ISSUE TITLE
Dummy input aligns only left

### ISSUE THREAD

**Issue by pkestefran** [google/blockly#3330]
**Describe the bug**

Dummy input currently does not align right (or center).
Last working in 2.20190722.1

**To Reproduce**

1. In blockly factory create a block similar to :

```javascript
Blockly.Blocks['block_type'] = {
  init: function() {
    this.appendDummyInput()
        .appendField("something long");
    this.appendDummyInput()
        .setAlign(Blockly.ALIGN_CENTRE)
        .appendField("a");
    this.appendDummyInput()
        .setAlign(Blockly.ALIGN_RIGHT)
        .appendField("a");
    this.setColour(230);
 this.setTooltip("");
 this.setHelpUrl("");
  }
};
```

**Expected behavior**

Fields in Dummy input should respect selected alignment.

**Screenshots**

Current master:
![2019-10-24_09h47_36](https://user-images.githubusercontent.com/18596276/67464257-54f38d00-f643-11e9-9e23-96c53eee7376.png)

2.20190722.1:
![2019-10-24_09h50_17](https://user-images.githubusercontent.com/18596276/67464581-da773d00-f643-11e9-9f25-6a95dfe512fa.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 70.0

**Comment by RoboErikG** [comment]
@rachel-fenichel looks like we're missing some logic for dummy input rows. Value inputs and statement inputs do center and right alignment correctly.

@pkestefran are you depending on the alignment in a live app or is this just something you noticed in the developer tools?

![image](https://user-images.githubusercontent.com/11066279/67502446-bb27e200-f63a-11e9-82b0-c36a520b2830.png)

**Comment by pkestefran** [comment]
@RoboErikG The behavior is the same in the live app. I have noticed this while testing new changes in blockly with custom blocks we have in our app. We have multiple right aligned dummy inputs within our blocks. For now we will stay with 2.20190722.1

**Comment by RoboErikG** [comment]
Thanks, that means we may need to do another patch then.

**Comment by samelhusseini** [comment]
We've fixed this and released a patch v3.20191014.4.
Thanks for reporting.

**Comment by pkestefran** [comment]
@samelhusseini I played a bit with test blocks in playground and noticed that the alignment is unfortunately still not respected in Zelos and Minimalist renderers. Geras and Thrasos are ok.

![2019-10-29_17h22_52](https://user-images.githubusercontent.com/18596276/67787552-11e54f80-fa71-11e9-9260-50f5074d84fe.png)

While we are ok, as we use Geras only, the behavior should be consistent. 
Can you please check? Thank you.

**Comment by samelhusseini** [comment]
Hey @pkestefran. The current POR is for Zelos is to not support external value inputs (only inline) like other renderers. We made the call to only add the logic in geras and thrasos.
I don't see a reason why the minimalist renderer shouldn't at least take somehow take into account its input's alignment properties (albeit it is a lower priority for us right now). @rachel-fenichel 

I've filed an issue to track this: https://github.com/google/blockly/issues/3361
