### ISSUE TITLE
Blocks unexpectedly scrolled up or down

### ISSUE THREAD

**Issue by stf-4js** [google/blockly#4414]
**Describe the bug**

Using updateToolbox() method on a workspace containing scrollbars unexpectedly moves the blocks found in the workspace if the toolbox doesn't have categories.

**To Reproduce**

1. Open the plunker for the issue : https://plnkr.co/plunk/siGoXNbADQ1tC6HI
    OR use the attached file
2. Follow the instructions found on the page

**Expected behavior**

Block should stay where it was as when a toolbox with categories is used

**Desktop**
 - OS: Windows
 - Browser: Chrome
 - Browser Version: 86.0.4240.111
- Blockly Version: google-blockly-ef8687d

**Additional files**
[issue.zip](https://github.com/google/blockly/files/5457522/issue.zip)

**Comment by alschmiedt** [comment]
Thanks for reporting! 

I think this is similar to #4340 and will work on adding a fix.

**Comment by alschmiedt** [comment]
This was fixed in #4415. And a [patch](https://github.com/google/blockly/releases/tag/3.20200924.4) was just released with the fix.

**Comment by stf-4js** [comment]
Working fine, thanks for the fix !

**Comment by janhink** [comment]
Hi, the problem is still there for sub-categories.

I updated the issue on Plunker: https://plnkr.co/edit/urbkFROTSdjSTQsY

Please have a look at it.
Best regards,

Jan
