### ISSUE TITLE
Update cursor position at the end of drags

### ISSUE THREAD

**Issue by rachel-fenichel** [google/blockly#8825]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Problem

Current keyboard experimentation code does this by listening for events. See `navigation.handleBlockDeleteByDrag`

### Request

If a block was dragged to the flyout or trash can, it will be deleted. Update the cursor location from `BlockDragStrategy.endDrag`.

Check whether comments can be deleted by dragging. If so, apply a similar change in `CommentDragStrategy.endDrag`.

**Comment by rachel-fenichel** [comment]
Follow up with https://github.com/google/blockly-keyboard-experimentation/issues/347 when this is complete.

**Comment by BenHenning** [comment]
I was testing this last week with #8981 and I'm pretty sure it is now fixed, but I may not have checked all relevant cases for dragging (I simply verified that dragging a block from the flyout onto the workspace and dragging a block within the workspace both maintain cursor position in the keyboard navigation plugin).

**Comment by rachel-fenichel** [comment]
Cursor position is still wrong after block deletion by drag--it is lost entirely and requires tabbing to get it back to the workspace.

This is not v12 blocking, so this issue is correctly tagged as part of feature complete for accessibility.

**Comment by BenHenning** [comment]
Dragging to delete was one of the cases I didn't check, so that makes sense.
