### ISSUE TITLE
Passive focus in mutator workspace does not update

### ISSUE THREAD

**Issue by joreneng** [google/blockly#9285]
### Check for duplicates

- [x] I have searched for similar issues before opening a new one.

### Description

Expected Behavior:
After leaving the mutator workspace, passive focus outline disappears and the active focus responds to the arrow keys based on the previous location of the focus when focus returns to the mutator workspace. This is based on the behaviour shown in the workspace.

Actual Behavior:
After leaving the mutator workspace, passive and active focus shows up in different locations after focus returns to the mutator workspace.

### Reproduction steps

1. Add a mutator block and add more inputs to the mutator block (to ensure that there is more than 1 input).
4. Navigate to the last block added in the mutator bubble/workspace.
5. Tab to move away from the mutator bubble (do not close the bubble).
6. Tab to move focus into the workspace until there is only a blue outline around the workspace.
7. Press the down arrow key.
8. Observe that both the active and passive focus exists.

### Stack trace

```shell

```

### Screenshots

https://github.com/user-attachments/assets/4f9b5aab-4b4c-4000-bc56-5e7f9d253839

**Comment by sappm01** [comment]
@gonfunko Can you confirm if this was already fixed?

**Comment by cpcallen** [comment]
This appears to be a bug in the focus manager—AIUI it shouldn't be possible to have both active and passive focus indicators in the same focus tree.

I can confirm that this still exists as of 5 August (google/blockly `develop` branch, commit 44e78b1).

**Comment by BenHenning** [comment]
Thanks for filing this @joreneng and for checking on it @cpcallen.

I can confirm I also ran into this when testing mutators, but hadn't filed a bug for it (I think I might've forgotten to, actually).

I agree that there's something quite odd happening here. It _should_ be impossible for both passive and active focus indicators to coexist, but it's not surprising that it could theoretically exist (it isn't the case that something actually holds passive focus here, just that its styling was never updated). I'm fairly certain this is a focus manager bug as @cpcallen mentioned, and will need investigating.

**Comment by gonfunko** [comment]
This thankfully no longer appears to repro.
